export const branchFormInputs = [
  {
    id: 1,
    name: "Branch Name",
    type: "text",
    // placeholder: "Branch name",
    label: "Branch Name",
    pattern: "^[A-Za-z0-9]{3,16}$",
    required: true,
  },
  {
    id: 2,
    name: "Code",
    type: "text",
    label: "Code",
    required: true,
  },
  {
    id: 3,
    name: "Region",
    type: "text",
    label: "Region",
  },
  {
    id: 4,
    name: "Hub",
    type: "text",
    label: "Hub",
    required: true,
  },
  {
    id: 5,
    name: "Vertical",
    type: "text",
    label: "Vertical",
    required: true,
  },
  {
    id: 6,
    name: "Zone",
    type: "text",
    label: "Zone",
    required: true,
  },
  {
    id: 7,
    name: "State",
    type: "text",
    label: "State",
    required: true,
  },
  {
    id: 8,
    name: "District",
    type: "text",
    label: "District",
    required: true,
  },
  {
    id: 9,
    name: "City",
    type: "text",
    label: "City",
    required: true,
  },
  {
    id: 10,
    name: "Building Name",
    type: "text",
    label: "Bulding Name",
    required: true,
  },
  {
    id: 11,
    name: "Pin Code",
    type: "number",
    label: "Pin Code",
    pattern:"^[1-9]{1}[0-9]{2}\\s{0, 1}[0-9]{3}$",
    required: true,
  },
  {
    id: 12,
    name: "Risk Category",
    type: "text",
    label: "Risk Category",
    required: true,
  },
  {
    id: 13,
    name: "Branch Locality",
    type: "text",
    label: "Branch Locality",
    required: true,
  },
  {
    id: 14,
    name: "Post Office",
    type: "text",
    label: "Post Office",
    required: true,
  },
  {
    id: 15,
    name: "Mail Address",
    type: "text",
    label: "Mail Adress",
    required: true,
  },
  {
    id: 16,
    name: "Contact Person",
    type: "text",
    label: "Contact Person",
    required: true,
  },
  {
    id: 17,
    name: "Mobile Number",
    type: "number",
    label: "Mobile Number",
    pattern:" [\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$",
    required:true,
  },
  {
    id: 18,
    name: "Branch Land Phone",
    type: "number",
    label: "Branch Land Phone",
    required: true,
  },
  {
    id: 19,
    name: "Branch Mobile",
    type: "number",
    label: "Branch Mobile",
    pattern:" [\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$",
    required: true,
  },
  {
    id: 20,
    name: "Current Status",
    type: "text",
    label: "Current Status",
    required: true,
  },
  {
    id: 21,
    name: "Support Type",
    type: "text",
    label: "Support Type",
    required: true,
  },
  {
    id: 22,
    name: "Connectivity Type",
    type: "text",
    label: "Connectivity Type",
    required: true,
  },
];