export const deviceFormInputs = [
    {
      id: 1,
      name: "Device ID",
      type: "text",
      // placeholder: "Device ID",
      label: "Device ID",
      required: true,
    },
    {
      id: 2,
      name: "Date of Installation",
      type: "date",
      label: "Date of Installation",
      required:true,
    },
    {
      id: 3,
      name: "Warranty Period",
      type: "date",
      label: "Warranty Period",
    },
    {
      id: 4,
      name: "Hardware Version",
      type: "text",
      label: "Hardware Version",
      required: true,
    },
    {
      id: 5,
      name: "Software Version",
      type: "text",
      label: "Software Version",
      required: true,
    },
    {
      id: 6,
      name: "IP Address",
      type: "text",
      label: "IP Address",
      // eslint-disable-next-line
      pattern:"^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$",
      required: true,
    },
    {
      id: 7,
      name: "Modem IP",
      type: "text",
      label: "Modem IP",
      required: true,
    },
    {
      id: 8,
      name: "WIFI SSID",
      type: "text",
      label: "Wifi SSID",
      required: true,
    },
    {
      id: 9,
      name: "Password",
      type: "text",
      label: "Password",
      required: true,
    },
    {
      id: 10,
      name: "GSM Number",
      type: "number",
      label: "Gsm Number",
      required: true,
    },
    {
      id: 11,
      name: "ZONE 1",
      type: "text",
      label: "ZONE 1",
      required: true,
    },
    {
      id: 12,
      name: "ZONE 2",
      type: "text",
      label: "ZONE 2",
      required: true,
    },
    {
      id: 13,
      name: "ZONE 3",
      type: "text",
      label: "ZONE 3",
      required: true,
    },
    {
      id: 14,
      name: "ZONE 4",
      type: "text",
      label: "ZONE 4",
      required: true,
    },
    {
      id: 15,
      name: "ZONE 5",
      type: "text",
      label: "ZONE 5",
      required: true,
    },
    {
      id: 16,
      name: "ZONE 6",
      type: "text",
      label: "ZONE 6",
      required: true,
    },
    {
      id: 17,
      name: "ZONE 7",
      type: "text",
      label: "ZONE 7",
      required: true,
    },
    {
      id: 18,
      name: "ZONE 8",
      type: "text",
      label: "ZONE 8",
      required:true,
    },
    {
      id: 19,
      name: "ZONE 9",
      type: "text",
      label: "ZONE 9",
      required: true,
    },
    {
      id: 20,
      name: "ZONE 10",
      type: "text",
      label: "ZONE 10",
      required: true,
    },
    {
      id: 21,
      name: "Last Updated",
      type: "date",
      label: "Last Updated",
      required: true,
    },
  ];